#!/bin/sh

BASE_PATH=`pwd`
echo "Existing files will be renamed with suffix .original"

[ -f ~/.zshrc ] && \mv -f ~/.zshrc ~/.zshrc.original
\ln -s $BASE_PATH/.zshrc ~

[ -f ~/.tmux.conf ] && \mv -f ~/.tmux.conf ~/.tmux.conf.original
\ln -s $BASE_PATH/.tmux.conf ~

echo "Done"
